{{- if eq .Values.cluster.provider "aws" }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.storageClass.name }}
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
{{- end }}