apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ilyde-workspace-replacepathregex
spec:
  replacePathRegex:
    regex: ^\/workspacesession\/(\w+)\/(.*)
    replacement: /$2
