replicaCount: 1
image:
  repository: ilyde/datasets
  pullPolicy: IfNotPresent
  tag: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 50051

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80


tolerations: []

affinity: {}
